version: '3.8'

services:
  dev-env:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ifrs9-dev-env
    volumes:
      - .:/workspace
    ports:
      - "8888:8888" # JupyterLab
      - "5000:5000" # MLflow UI
      - "8000:8000" # MLOps FastAPI
    environment:
      # Passamos a variável do .env para dentro do Python (Pipeline Orchestrator)
      - USE_GPU=${USE_GPU:-False}
    # Inicia o JupyterLab e o servidor do MLflow em background
    command: >
      bash -c "jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root --ServerApp.token='' --ServerApp.password='' &
               mlflow server --host 0.0.0.0 --port 5000"